#!/usr/bin/env python3
"""Extract a PICO-8 cart's raw sound data (the 0x3100 music + 0x3200 sfx RAM
regions) from a .p8.png (or .p8) into the `audio_data.rs` a game feeds to the
shared software synth. No conversion: the synth reads PICO-8's own byte layout.

Usage:
    python3 tools/p8_audio.py <cart.p8.png|cart.p8> <out_dir>

Emits <out_dir>/audio_data.rs with SFX_DATA ([[u8; 68]; 64]) and MUSIC_DATA
([[u8; 4]; 64]).
"""
import os
import sys


def png_rom(path):
    """Decode the 32 KiB cart ROM hidden in a .p8.png (2 low bits per channel)."""
    from PIL import Image

    im = Image.open(path).convert("RGBA")
    px = im.getdata()
    rom = bytearray(0x8000)
    for i, (r, g, b, a) in enumerate(px):
        if i >= 0x8000:
            break
        rom[i] = ((a & 3) << 6) | ((r & 3) << 4) | ((g & 3) << 2) | (b & 3)
    return bytes(rom)


def text_rom(path):
    """Build the sfx/music ROM regions from a .p8 text cart."""
    rom = bytearray(0x8000)
    cur = None
    sfx_i = mus_i = 0
    with open(path, encoding="latin-1") as f:
        for line in f:
            line = line.strip()
            if line.startswith("__") and line.endswith("__"):
                cur = line
                continue
            if not line:
                continue
            if cur == "__sfx__" and sfx_i < 64:
                b = bytes.fromhex(line[:8])
                base = 0x3200 + sfx_i * 68
                for n in range(32):
                    h = line[8 + n * 5 : 13 + n * 5]
                    pitch, wave, vol, eff = int(h[0:2], 16), int(h[2], 16), int(h[3], 16), int(h[4], 16)
                    w = ((wave & 7) << 6) | (0x8000 if wave >= 8 else 0) | pitch | (vol << 9) | (eff << 12)
                    rom[base + n * 2] = w & 0xFF
                    rom[base + n * 2 + 1] = w >> 8
                rom[base + 64 : base + 68] = b
                sfx_i += 1
            elif cur == "__music__" and mus_i < 64:
                flags = int(line[:2], 16)
                ch = bytes.fromhex(line[3:11])
                base = 0x3100 + mus_i * 4
                for c in range(4):
                    rom[base + c] = ch[c] | ((flags >> c) & 1) << 7
                mus_i += 1
    return bytes(rom)


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    cart, out_dir = sys.argv[1], sys.argv[2]
    rom = png_rom(cart) if cart.endswith(".png") else text_rom(cart)
    music = rom[0x3100:0x3200]
    sfx = rom[0x3200:0x4300]

    lines = ["// Auto-generated by tools/p8_audio.py -- raw PICO-8 sound RAM. Do not edit.", ""]
    lines.append("/// 64 SFX, 68 bytes each: 32 notes (u16 LE: pitch 0-5, wave 6-8, vol 9-11,")
    lines.append("/// effect 12-14, custom bit 15) then editor-mode/filters, speed, loop start, loop end.")
    lines.append("pub static SFX_DATA: [[u8; 68]; 64] = [")
    for i in range(64):
        s = sfx[i * 68 : (i + 1) * 68]
        lines.append("    [" + ", ".join(str(b) for b in s) + "],")
    lines.append("];")
    lines.append("")
    lines.append("/// 64 music patterns, 4 channel bytes each: sfx index 0-5, bit 6 = channel off,")
    lines.append("/// bit 7 = loop-start / loop-end / stop flag on bytes 0 / 1 / 2.")
    lines.append("pub static MUSIC_DATA: [[u8; 4]; 64] = [")
    for i in range(64):
        m = music[i * 4 : (i + 1) * 4]
        lines.append("    [" + ", ".join(str(b) for b in m) + "],")
    lines.append("];")
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "audio_data.rs"), "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
